name: portofolio
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/ubuntu/.kube/config

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          echo "Build docker image for fe dan be.."
          docker build -f Dockerfile.backend -t monet1/portofolio-be:${{ github.sha }} -t monet1/portofolio-be:latest .
          docker build -f Dockerfile.frontend -t monet1/portofolio-fe:${{ github.sha }} -t monet1/portofolio-fe:latest .

      - name: Push docker image to registry container
        run: |
          echo "Push docker image to registry.."
          docker push -a monet1/portofolio-be
          docker push -a monet1/portofolio-fe
      - name: "Apply k3s manifests.."
        run: |
          kubectl apply -k k8s/
      - name: Update deployment k3s
        run: |
          echo "Update deploy k3s.."
          kubectl set image deployment/backend  backend=monet1/portofolio-be:${{ github.sha }} -n porto-lab
          kubectl set image deployment/frontend frontend=monet1/portofolio-fe:${{ github.sha }} -n porto-lab

          kubectl rollout status deployment/backend -n porto-lab
          kubectl rollout status deployment/frontend -n porto-lab
      - name: Purge Cloudflare cache
        run: |
          echo "Purging Cloudflare cache.."
          curl -sf -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID}}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":}'
